// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZxaidYOlcTDdziTA9cFk-OzjROZdcCq8',
    appId: '1:1068582857009:android:88ae0f4b5cd4bc51e96810',
    messagingSenderId: '1068582857009',
    projectId: 'lab2-d08f6',
    storageBucket: 'lab2-d08f6.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAyMTd02_5gCE8lhdyAf1snIszjv8NTbk',
    appId: '1:1068582857009:web:c5d8a942b2d4d054e96810',
    messagingSenderId: '1068582857009',
    projectId: 'lab2-d08f6',
    authDomain: 'lab2-d08f6.firebaseapp.com',
    storageBucket: 'lab2-d08f6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDk2H0WxJsprFLf5fbxzYecyKd1uwRqFw',
    appId: '1:1068582857009:ios:50c564a71d4740bfe96810',
    messagingSenderId: '1068582857009',
    projectId: 'lab2-d08f6',
    storageBucket: 'lab2-d08f6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDk2H0WxJsprFLf5fbxzYecyKd1uwRqFw',
    appId: '1:1068582857009:ios:50c564a71d4740bfe96810',
    messagingSenderId: '1068582857009',
    projectId: 'lab2-d08f6',
    storageBucket: 'lab2-d08f6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAyMTd02_5gCE8lhdyAf1snIszjv8NTbk',
    appId: '1:1068582857009:web:fc436546dafc7dc8e96810',
    messagingSenderId: '1068582857009',
    projectId: 'lab2-d08f6',
    authDomain: 'lab2-d08f6.firebaseapp.com',
    storageBucket: 'lab2-d08f6.firebasestorage.app',
  );

}